### ISSUE TITLE
쿠폰 수정 로직 개선 및 쿠폰 전체 조회 기능 보완

### ISSUE THREAD

**Issue by ohsutinn** [sepang-pang/Issue-Coupon-Service#10]
## Description
쿠폰 전체 조회 기능 : 누락된 기능 구현
쿠폰 수정 기능 : 잘못된 반환 내용 수정, 의도와 다른 조건문 수정, 쿠폰 수정 간 이름 중복 검증

## Todo
- [x] 쿠폰 조회 간 반환 데이터 중 쿠폰의 이름을 추가합니다.
- [x] 쿠폰 수정 성공 메시지를 "쿠폰 수정 성공"으로 교체합니다.
- [x] 쿠폰 수정 간 null 값이 넘어올 때 해당 데이터는 업데이트 하지 않도록합니다.
- [x] 쿠폰 수정 간 중복된 이름이 없는지 검증합니다.

## ETC
기타사항
