### ISSUE TITLE
사용자 권한을 활용한 쿠폰 발급 및 조회 기능 개발

### ISSUE THREAD

**Issue by JihyeChu** [sepang-pang/Issue-Coupon-Service#12]
## Description
사용자(USER) 권한을 가진 사용자가 쿠폰을 조회하고 발급하는 기능을 구현할 것이다.
이 기능에는 사용자가 발급받기 위한 쿠폰 전체 조회와 상세 조회로 나뉘고, 본인이 발급한 쿠폰의 전체 조회로 나뉜다. 여기에 더해 쿠폰 발급 기능 또한 포함된다.

## Todo
- [x] 사용자는 발급받고자 하는 쿠폰의 조회가 가능해야 한다.
- [x] 사용자는 쿠폰을 발급할 수 있어야 한다.
- [x] 쿠폰 발급 시 검증 단계를 거쳐야 한다. (만료, 잔여쿠폰, 중복)
- [x] 사용자는 본인이 발급한 쿠폰의 조회가 가능해야 한다.

## ETC
기타사항
