### ISSUE TITLE
쿠폰 유효성 검사 로직 리팩토링 및 Secured 어노테이션 업데이트

### ISSUE THREAD

**Issue by ohsutinn** [sepang-pang/Issue-Coupon-Service#18]
## Description
@RequestMapping("/common") 제거, @Secured 어노테이션의 사용법 변경, 그리고 중복 쿠폰 검증 로직 등을 수정할 계획입니다.

## Todo
- [x] @RequestMapping("/common")` 어노테이션 제거
- [x] @Secured("USER")`를 `@Secured(USER)`로 변경
- [x] 쿠폰 중복 검증 로직 개선

## ETC
기타사항
