### ISSUE TITLE
쿠폰 재고 감소 동시성 제어 이슈

### ISSUE THREAD

**Issue by ohsutinn** [sepang-pang/Issue-Coupon-Service#20]
## Description
다수의 회원이 동시에 하나의 쿠폰을 발급받으려 할 때 재고 감소 처리에 대한 동시성 문제가 발생.

실제 쿠폰 재고 감소량과 실제 발급 쿠폰 수가 일치 하지 않으며, 예상 발급 수 보다 현저히 적은 수량으로 발급되는 것을 확인

## Todo
- [x] 데이터베이스 레벨에서의 잠금 설정을 검토하여, 동시에 같은 쿠폰에 대한 접근을 제어
- [x] 동시성을 고려한 테스트 케이스를 작성하여, 개선된 로직의 동작을 검증
- [x] 동시 요청 시 시스템의 성능을 테스트

## ETC
기타사항
