### ISSUE TITLE
쿠폰 관리 시스템 개선

### ISSUE THREAD

**Issue by ohsutinn** [sepang-pang/Issue-Coupon-Service#40]
## Description

쿠폰의 발급 마감 시간과 사용 만료 시간을 명확히 구분하여 관리하는 기능, 쿠폰의 세부 내용을 설명하는 컬럼 추가, 그리고 쿠폰의 상태값을 표현하는 ENUM 클래스 도입의 필요성을 느낌.

## Todo
- [x] 쿠폰 발급 마감 시간과 사용 만료 시간을 분리
- [x] 쿠폰 설명 및 내용 컬럼 추가
- [x] ACTIVE, INACTIVE, EXPIRED 등으로 쿠폰의 상태값을 표시

## ETC
기타사항
