### ISSUE TITLE
로그인 및 메인 페이지 구현

### ISSUE THREAD

**Issue by ohsutinn** [sepang-pang/Issue-Coupon-Service#44]
## Description
쿠폰 서비스 이용을 위한 로그인 및 메인 페이지를 구현합니다. 사용자가 편리하게 로그인할 수 있고, 주요 쿠폰 정보를 효과적으로 확인할 수 있는 인터페이스를 제공할 예정입니다.

## Todo
- [x] Google, Kakao, Naver 등의 Oauth2.0 인증 버튼 구현
- [x] 쿠폰 발급을 위한 메인페이지 구현
- [x] 오픈 예정 쿠폰, 종료된 쿠폰 페이지 구현
- [x] 오픈 예정 쿠폰, 종료된 쿠폰 페이지 구현 간 페이지네이션 기능 활용
- [x] 마이 페이지 구현
- [x] 마이 페이지 내에 내 프로필 및 내 쿠폰 조회를 함께 할 수 있어야 함

## ETC
기타사항
