### ISSUE TITLE
마이페이지 프로필 조회 및 보유 쿠폰 조회 자바스크립트 구현

### ISSUE THREAD

**Issue by ohsutinn** [sepang-pang/Issue-Coupon-Service#49]
## Description
마이페이지에서 유저 본인의 프로필 조회 및 보유 쿠폰 조회에 대한 자바스크립트를 구현할 것입니다.

## Todo
- [x] 로그인한 유저의 프로필 정보를 조회할 수 있어야 한다.
- [x] 유저가 보유한 쿠폰을 조회할 수 있다.
- [x] 한 번에 5개까지 조회가 가능하며, 이를 넘어가면 페이징 처리를 수행한다.

## ETC
기타사항
