### ISSUE TITLE
메인 페이지 쿠폰 조회 개선 및 발급 기능 구현

### ISSUE THREAD

**Issue by ohsutinn** [sepang-pang/Issue-Coupon-Service#52]
## Description
메인 페이지에서 현재 진행 중인 쿠폰을 조회할 때, 쿠폰이 존재하지 않을 경우 사용자에게 관련 메시지를 출력하는 기능을 추가합니다. 

또한, 사용자가 쿠폰을 발급받을 수 있도록 하는 자바스크립트 코드를 작성합니다.

## Todo
- [x] 메인 페이지에서 쿠폰이 존재하지 않을 경우 메시지를 출력하는 기능 추가
- [x] 사용자가 쿠폰을 발급받을 수 있도록 자바스크립트 코드 작성
- [x] 인증되지 않거나 권한이 없는 유저가 쿠폰을 발급받을 시 메시지 출력과 함께 로그인 페이지로 리다이렉트

## ETC
기타사항
