### ISSUE TITLE
관리자 페이지 작성

### ISSUE THREAD

**Issue by ohsutinn** [sepang-pang/Issue-Coupon-Service#63]
## Description
관리자 메인 페이지에서 쿠폰 조회와 쿠폰 등록 버튼을 포함하는 UI를 구현합니다. 각 버튼은 클릭 시 관련 페이지로 넘어가야 합니다.

또한 쿠폰 조회 페이지에서 모든 쿠폰을 표시해야 하며, 각 쿠폰에는 수정 및 삭제 버튼이 활성화되어 있어야 합니다.

해당 수정 및 삭제 버튼을 누르면 관련 기능이 수행되어야 합니다.

## Todo
- [x] 쿠폰 조회 및 쿠폰 등록 버튼을 포함한 HTML 작성
- [x] 각 버튼에 이벤트 리스너를 추가하여 적절한 페이지로 이동하도록 구현
- [x] 각 쿠폰마다 수정 및 삭제 버튼을 포함하여 설계
- [x] 수정 버튼 클릭 시 쿠폰 수정 페이지로 이동
- [x] 삭제 버튼 클릭 시 모달 창 출력 후 쿠폰 삭제 여부 확인
- [x] 삭제를 시도하면 쿠폰을 삭제하고, 페이지를 새로 고침

## ETC
기타사항
