### ISSUE TITLE
코드 리팩토링 및 경로 재설정

### ISSUE THREAD

**Issue by ohsutinn** [sepang-pang/Issue-Coupon-Service#68]
## Description
기능별 코드 분리 및 경로 재설정을 통해 코드의 가독성과 유지보수성을 향상시키기 위한 리팩토링 작업

## Todo
- [x] 불필요한 API 메서드 삭제
- [x] 라우팅 메서드 분리
- [x] 네비게이션 바 HTML 파일 이름 변경
- [x] 쿠폰 조회 메서드 리팩토링
- [x] `CouponOneForm` 클래스 이름을 `CouponSummaryForm`으로 변경

## ETC
기타사항
