### ISSUE TITLE
네비게이션 접근성 개선 및 메인 페이지 오픈 예정 쿠폰 조회 기능 추가

### ISSUE THREAD

**Issue by ohsutinn** [sepang-pang/Issue-Coupon-Service#70]
## Description
사용자가 언제 쿠폰을 받을 수 있는지 명확하게 알 수 있도록 하고, 회원과 비회원에게 필요한 정보를 쉽게 제공할 수 있도록 한다.

## Todo
- [x] 가장 빠른 시일 내에 오픈되는 쿠폰을 조회하는 로직 구현
- [x] 메인 페이지에서 오픈 예정 쿠폰 정보 출력 기능 구현
- [x] 네비게이션 접근성 개선

## ETC
기타사항
