### ISSUE TITLE
관리자 권한을 활용한 쿠폰 관리 기능 개발

### ISSUE THREAD

**Issue by ohsutinn** [sepang-pang/Issue-Coupon-Service#8]
## Description
관리자 권한을 가진 사용자가 쿠폰을 관리할 수 있도록 하는 기능을 구현할 것이다.
이 기능에는 쿠폰의 생성, 수정, 삭제 및 관리자 본인이 발급한 쿠폰을 조회하는 기능이 포함된다.

## Todo
- [x] 관리자는 쿠폰을 생성할 수 있어야 한다.
- [x] 쿠폰 생성 간 만료기한을 지정할 수 있다.
- [x] 쿠폰은 논리 삭제로 제거가 된다

## ETC
기타사항
